name: dispatch.service-configure

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true

jobs:
  setup:
    name: Set service id
    runs-on: ubuntu-latest
    outputs:
      service_id: ${{ steps.service_id.outputs.value }}

    steps:
      - id: service_id
        run: |
          echo "::set-output name=value::results"

  image-builder-service-configure:
    needs: setup
    name: Dispatch service-configure event to image builder
    runs-on: ubuntu-latest

    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.IMAGE_BUILDER_TOKEN }}
          repository: smartassert/image-builder
          event-type: service-configure
          client-payload: |
            {
              "service_id": "${{ needs.setup.outputs.service_id }}",
              "build_configuration": "{\"version\": \"${{ github.event.inputs.version }}\"}"
            }
